//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QC.rc
//
#define IDC_CHANGE                      3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QC_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDD_ALARM_DLG                   130
#define IDD_DIALOGLOGIN                 131
#define IDD_DIALOGCHANGE                132
#define IDD_DIALOGMODIFY                133
#define IDD_DIALOGNEWUSER               134
#define IDD_DIALOGSELECTSIGNAL          135
#define IDB_VIEWMODE16                  136
#define IDB_VIEWMODE1                   137
#define IDB_VIEWMODE4                   138
#define IDD_DIALOG_PTZ                  139
#define IDC_CH1                         1000
#define IDC_CH2                         1001
#define IDC_CH3                         1002
#define IDC_CH4                         1003
#define IDC_CH5                         1004
#define IDC_CH6                         1005
#define IDC_CH7                         1006
#define IDC_CH8                         1007
#define IDC_CH9                         1008
#define IDC_CH10                        1009
#define IDC_CH11                        1010
#define IDC_CH12                        1011
#define IDC_CH13                        1012
#define IDC_CH14                        1013
#define IDC_CH15                        1014
#define IDC_CH16                        1015
#define IDC_DWELL_LIST                  1016
#define IDC_FINISH                      1017
#define IDC_ALARM_IN                    1018
#define IDC_RESET                       1019
#define IDC_INSTALL_DRIVER              1020
#define IDC_ALARM_OUT                   1021
#define IDC_ALARM_RELAY                 1022
#define IDC_DWELL_LIST_RESOLUTION       1023
#define IDC_CARD_SERIAL_NUMBER          1024
#define IDC_SUBSYSTEM_ID_RES            1025
#define IDC_INSTRALL_DRIVER_RES         1026
#define IDC_PASS_WORD_RES               1027
#define IDC_CARD_TYPE_VIEW              1034
#define IDC_CARD_ID_VIEW                1035
#define IDC_ALARM_RELAY_RES             1036
#define IDC_AUTO_DWELL_RES              1037
#define IDC_ALARM_TEST_BUTTON           1038
#define IDC_DISPLAY_RES                 1039
#define IDC_RESET_RES                   1040
#define IDC_ALARM_OUT_RES               1041
#define IDC_ALARM_IN_RES                1042
#define IDC_DISPLAY                     1043
#define IDC_ALARM_IN_CAPTURE            1043
#define IDC_ALARM_OUT_CAPTURE           1044
#define IDC_ALARM_RELAY_CAPTURE         1045
#define IDC_ALARM_IN_1                  1055
#define IDC_LABLE_SWITCH                1056
#define IDC_VIDEO_FORMAT_PAL            1057
#define IDC_VIDEO_FORMAT_NTSC           1058
#define IDC_ALARM_IN_2                  1059
#define IDC_PRODUCT_SN                  1059
#define IDC_ALARM_IN_3                  1060
#define IDC_ACCEPT                      1060
#define IDC_ALARM_IN_4                  1061
#define IDC_REJECT                      1061
#define IDC_ALARM_IN_5                  1062
#define IDC_PRODUCT_SN2                 1062
#define IDC_ALARM_IN_6                  1063
#define IDC_AUTO_DWELL_CAPTURE          1063
#define IDC_ALARM_IN_7                  1064
#define IDC_ALARM_IN_8                  1065
#define IDC_ALARM_IN_9                  1066
#define IDC_ALARM_IN_10                 1067
#define IDC_ALARM_IN_11                 1068
#define IDC_ALARM_IN_12                 1069
#define IDC_ALARM_IN_13                 1070
#define IDC_ALARM_IN_14                 1071
#define IDC_ALARM_IN_15                 1072
#define IDC_ALARM_IN_16                 1073
#define IDC_LAMP_ALARM_OUT_1            1074
#define IDC_LAMP_ALARM_OUT_2            1075
#define IDC_LAMP_ALARM_OUT_3            1076
#define IDC_LAMP_ALARM_OUT_4            1077
#define IDC_LAMP_ALARM_J                1078
#define IDC_AUTO_TEST                   1079
#define IDC_EDITUSER                    1080
#define IDC_EDITPASSWORD                1081
#define IDC_EDITCONFIRM                 1081
#define IDC_EDITNEW                     1082
#define IDC_LIST                        1084
#define IDC_BUTTONADD                   1085
#define IDC_BUTTONREMOVE                1086
#define IDC_EDITPASS                    1087
#define IDC_RADIO1                      1087
#define IDC_RADIO2                      1088
#define IDC_RADIO3                      1089
#define IDC_CHECKPSW                    1090
#define IDC_RADIO4                      1090
#define IDC_RADIO5                      1091
#define IDC_RADIO6                      1092
#define IDC_RADIO7                      1093
#define IDC_RADIO8                      1094
#define IDC_RADIO9                      1095
#define IDC_RADIO10                     1096
#define IDC_RADIO11                     1097
#define IDC_RADIO12                     1098
#define IDC_RADIO13                     1099
#define IDC_RADIO14                     1100
#define IDC_RADIO15                     1101
#define IDC_RADIO16                     1102
#define IDC_STATIC_YINPING              1103
#define IDC_RADIO_PREVIEW               1104
#define IDC_RADIO_CAPTURE               1105
#define IDC_RADIO_NET                   1106
#define IDC_VIEWMODE1                   1107
#define IDC_VIEWMODE4                   1108
#define IDC_VIEWMODE16                  1109
#define IDC_BMP_VIEWMODE1               1110
#define IDC_BMP_VIEWMODE4               1111
#define IDC_BMP_VIEWMODE16              1112
#define IDC_BTN_NEXTVIEW                1113
#define IDC_STATIC_CURRENTCHANNEL       1115
#define IDC_CURRENTCHANNEL              1116
#define IDC_3316FPJ                     1117
#define IDC_BUTTON_PTZ                  1119
#define IDC_BUTTONPRE                   1120
#define IDC_BUTTONSAVEPRE               1121
#define IDC_BUTTONUP                    1122
#define IDC_BUTTONLEFT                  1123
#define IDC_BUTTONRIGHT                 1124
#define IDC_BUTTONSTOP                  1125
#define IDC_BUTTONDOWN                  1126
#define IDC_BUTTONDEL                   1128
#define IDC_RADIOFOCUS                  1129
#define IDC_RADIOZOOM                   1130
#define IDC_RADIOAIRIS                  1131
#define IDC_BUTTON_SAVESETTING          1132
#define IDC_TEST_PTZ                    1133
#define IDC_TEST_PTZ_RES                1134
#define IDC_AUDIO_RES                   1136
#define IDC_AUDIO                       1137
#define IDC_STATIC_TESTID               1139
#define IDC_STATIC_PASS                 1140
#define IDC_RADIO_CIF                   1141
#define IDC_RADIO_D1                    1142
#define IDC_BTN_APPLY                   1143
#define IDC_STATIC_VIDEOFORMAT          1144
#define IDC_PROGRESS_SIZECHANGE         1145
#define IDC_COMBO_D1                    1146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
