//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVUI.rc
//
#define IDD_IVRULE                      1000
#define IDC_RULE                        1000
#define IDS_OK                          1000
#define IDD_IVALARMOUT                  1001
#define IDC_ALARMOUT                    1001
#define IDS_CANCEL                      1001
#define IDS_Cancel                      1001
#define IDD_IVSCHUDULE                  1002
#define IDC_BUTTON3                     1002
#define IDC_SCHUDULE                    1002
#define IDS_PREV                        1002
#define IDS_Prev                        1002
#define IDS_Previous                    1002
#define IDD_IVTAB                       1003
#define IDS_NEXT                        1003
#define IDS_Next                        1003
#define IDC_SCHUDULE_CAMERA_TREE        1004
#define IDD_IVFUNCTIONSEL               1004
#define IDS_CLOSE                       1004
#define IDS_Close                       1004
#define IDC_ALARMOUT_CAMERA_TREE        1005
#define IDS_FINISH                      1005
#define IDS_Finish                      1005
#define IDC_RULE_CAMERA_TREE            1006
#define IDS_Apply                       1006
#define IDC_NOUSE_HOLD                  1007
#define IDS_Rule_Tree_Group             1007
#define IDC_USE_HOLD                    1008
#define IDD_ZONEADV                     1008
#define IDD_STAGECHANGEADV              1009
#define IDC_ALARM_HOLD_TIME             1010
#define IDD_LINEADV                     1010
#define IDC_CHECK1                      1011
#define IDD_FILTER                      1011
#define IDC_CHECK2                      1012
#define IDC_LIST1                       1012
#define IDR_Camera_Menu                 1012
#define IDC_CHECK3                      1013
#define IDC_RULENAME_EDIT               1013
#define IDR_Rule_Menu                   1013
#define IDC_CHECK4                      1014
#define IDS_TYPE                        1014
#define IDC_V_VIEW                      1014
#define IDC_CHECK5                      1015
#define IDC_P_VIEW                      1015
#define IDC_CHECK6                      1016
#define IDC_CHECK7                      1017
#define IDC_CHECK8                      1018
#define IDC_CHECK9                      1019
#define IDC_IDC_LOITERS_EDIT            1019
#define IDC_CHECK10                     1020
#define IDC_LEFTBEHIND_EDIT             1020
#define IDC_RULENAME                    1021
#define IDC_VIEW                        1022
#define IDC_CURSOR_ADD                  1022
#define IDC_OBJECT                      1023
#define IDC_CHECK_PERSON                1024
#define IDC_CURSOR_CLEAR                1024
#define IDC_CHECK_VEHICLE               1025
#define IDD_Add_Edit_Rule_Main          1025
#define IDC_CHECK_OTHER                 1026
#define IDC_CHECK_ALL                   1027
#define IDC_TIME                        1028
#define IDC_CHECK_Light_on              1028
#define IDC_LOITERS                     1029
#define IDC_CHECK_Light_off             1029
#define IDC_LEFTBEHIND                  1030
#define IDC_Event                       1031
#define IDC_CHECK_Montion               1032
#define IDC_CHECK_Other2                1033
#define IDC_CHECK_Anything              1034
#define IDC_EDIT1                       1035
#define IDC_FILTER_ON                   1036
#define IDC_FILTER_OFF                  1037
#define IDC_SPIN1                       1038
#define IDC_EDIT2                       1039
#define IDC_Multiplier                  1040
#define IDC_IV_Tab_Group                1041
#define IDC_Add_CHECK                   1042
#define IDC_Erase_CHECK                 1043
#define IDC_Rule_Group                  1044
#define IDC_Schudule_Group              1045
#define IDC_AlarmOut_Group              1046
#define IDC_AlarmOut_Group2             1046
#define IDC_Adv_BT                      1048
#define IDC_Filter_BT                   1049
#define IDC_Simulation_BT               1050
#define IDC_Line_Check                  1051
#define IDC_Zone_Check                  1052
#define IDC_Select_Check                1053
#define IDC_Right_Check                 1054
#define IDC_Left_Check                  1055
#define IDC_Both_Check                  1056
#define IDC_Colour_BT                   1057
#define IDC_Rectangle_Check             1058
#define IDC_Polygon_Check               1059
#define IDC_AlarmHold_Group             1060
#define IDC_Choose_Alarm_Group          1061
#define IDC_Alarm_Occur_STATIC          1063
#define IDC_Apply_BT                    1064
#define IDS_Invade                      3006
#define IDS_Leave_Disappear             3007
#define IDS_LeftBehind                  3008
#define IDS_Loiters                     3009
#define IDS_Statistic                   3010
#define IDS_Vehicle_Retrograde          3011
#define IDS_Illegal_Parking             3012
#define IDS_Stage_Change                3013
#define IDS_Type                        3014
#define IDS_Description                 3015
#define IDS_IV_Name_Des                 3016
#define IDS_STRING1017                  3017
#define IDS_STRING1018                  3018
#define IDS_STRING1019                  3019
#define IDS_STRING1020                  3020
#define IDS_STRING1021                  3021
#define IDS_STRING1022                  3022
#define IDS_STRING1023                  3023
#define IDS_STRING1024                  3024
#define IDS_STRING1025                  3025
#define IDS_RuleName                    3026
#define IDS_View                        3027
#define IDS_Vertical_View               3028
#define IDS_Parallel_View               3029
#define IDS_Object                      3030
#define IDS_Object_Person               3031
#define IDS_Object_Vehicle              3032
#define IDS_Object_Other                3033
#define IDS_Object_All                  3034
#define IDS_Time_S                      3035
#define IDS_Loiters_Time                3036
#define IDS_LeftBehind_Time             3037
#define IDS_RuleName_Alarm              3038
#define IDS_Object_Alarm                3039
#define IDS_Event                       3040
#define IDS_Event_Light_on              3041
#define IDS_Event_Light_off             3042
#define IDS_Event_Montion               3043
#define IDS_Event_Other                 3044
#define IDS_Event_Anything              3045
#define IDS_Filter_MinObj               3046
#define IDS_Filter_MaxObj               3047
#define IDS_Filter_Size_Change          3048
#define IDS_Filter_Shape_Direction      3049
#define IDS_Filter_MinObj_Info          3050
#define IDS_Filter_MaxObj_Info          3051
#define IDS_Filter_MaxxObj_Info         3051
#define IDS_Filter_Size_Change_Info     3052
#define IDS_Filter_Shape_Direction_Info 3053
#define IDS_Filter_Head_Type            3054
#define IDS_Filter_Head_State           3055
#define IDS_Filter_On                   3056
#define IDS_Filter_Off                  3057
#define IDS_Schu_Week_Sun               3058
#define IDS_Schu_Week_Mon               3059
#define IDS_Schu_Week_Tue               3060
#define IDS_Schu_Week_Wed               3061
#define IDS_Schu_Week_Thu               3062
#define IDS_Schu_Week_Fri               3063
#define IDS_Schu_Week_Sat               3064
#define IDS_Alarm_Out_Group             3065
#define IDS_Alarm_Hold_Group            3066
#define IDS_Alarm_Not_Hold              3067
#define IDS_Alarm_Hold_Des              3068
#define IDS_Alarm_Choose_Group          3069
#define IDS_AlarmOut_Record             3070
#define IDS_AlarmOut_FullScreen         3071
#define IDS_AlarmOut_Relay              3072
#define IDS_AlarmOut_Sensor             3073
#define IDS_AlarmOut_AutoMail           3074
#define IDS_AlarmOut_EMAP               3075
#define IDS_AlarmOut_Buzzer             3076
#define IDS_AlarmOut_SnapScreen         3077
#define IDS_AlarmOut_PlaySound          3078
#define IDS_AlarmOut_TelphoneCall       3079
#define IDS_Filter_Multiplier           3080
#define IDS_STRING3082                  3081
#define IDS_Schedule_Add                3081
#define IDS_STRING3083                  3082
#define IDS_Schedule_Erase              3082
#define IDS_STRING3084                  3083
#define IDS_Schedule_Tree_Group         3083
#define ID__NEW                         32771
#define ID_RULE_ENABLEALLRULE           32772
#define ID_RULE_DISABLEALLRULE          32773
#define ID_RULE_USE                     32774
#define ID_RULE_SHOWOBJECT              32775
#define ID_RULE_SHOWTRACE               32776
#define ID_RULE_SHOWOBJTRACE            32777
#define ID_RULE_DELETERULE              32778
#define ID_RULE_EDITRULE                32779
#define ID_RULE_RENAMERULE              32780
#define ID_RULE_ENABLERULE              32781
#define ID_RULE_DISABLERULE             32782
#define ID_SCHUDULE_FULL                32783
#define ID_SCHUDULE_EMPTY               32784
#define ID_SCHUDULE_COPY                32785
#define ID_SCHUDULE_PASTE               32786
#define ID_SCHUDULE_USETOALL            32787
#define ID_NEW                          32788
#define ID_RULE_NEWRULE                 32789
#define ID_SCHUDULE                     32790
#define ID_ALARMOUT                     32791
#define ID_Alarm_FULL                   32792
#define ID_Alarm_EMPTY                  32793
#define ID_Alarm_COPY                   32794
#define ID_Alarm_PASTE                  32795
#define ID_Alarm_USETOALL               32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1026
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
