//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVUI.rc
//
#define IDD_IVRULE                      1000
#define IDC_RULE                        1000
#define IDS_OK                          1000
#define IDD_IVALARMOUT                  1001
#define IDC_ALARMOUT                    1001
#define IDS_CANCEL                      1001
#define IDS_Cancel                      1001
#define IDD_IVSCHUDULE                  1002
#define IDC_BUTTON3                     1002
#define IDC_SCHUDULE                    1002
#define IDS_PREV                        1002
#define IDS_Prev                        1002
#define IDS_Previous                    1002
#define IDD_IVTAB                       1003
#define IDS_NEXT                        1003
#define IDS_Next                        1003
#define IDC_SCHUDULE_CAMERA_TREE        1004
#define IDD_IVFUNCTIONSEL               1004
#define IDS_CLOSE                       1004
#define IDS_Close                       1004
#define IDC_ALARMOUT_CAMERA_TREE        1005
#define IDS_FINISH                      1005
#define IDS_Finish                      1005
#define IDC_RULE_CAMERA_TREE            1006
#define IDS_Invade                      1006
#define IDC_NOUSE_HOLD                  1007
#define IDS_Leave_Disappear             1007
#define IDC_USE_HOLD                    1008
#define IDS_LeftBehind                  1008
#define IDD_ZONEADV                     1008
#define IDS_Loiters                     1009
#define IDD_STAGECHANGEADV              1009
#define IDC_ALARM_HOLD_TIME             1010
#define IDS_Statistic                   1010
#define IDD_LINEADV                     1010
#define IDC_CHECK1                      1011
#define IDS_Vehicle_Retrograde          1011
#define IDD_FILTER                      1011
#define IDC_CHECK2                      1012
#define IDC_LIST1                       1012
#define IDS_Illegal_Parking             1012
#define IDC_CHECK3                      1013
#define IDS_Stage_Change                1013
#define IDC_RULENAME_EDIT               1013
#define IDC_CHECK4                      1014
#define IDS_TYPE                        1014
#define IDS_Type                        1014
#define IDC_V_VIEW                      1014
#define IDC_CHECK5                      1015
#define IDS_Description                 1015
#define IDC_P_VIEW                      1015
#define IDC_CHECK6                      1016
#define IDS_IV_Name_Des                 1016
#define IDC_CHECK7                      1017
#define IDS_STRING1017                  1017
#define IDC_CHECK8                      1018
#define IDS_STRING1018                  1018
#define IDC_CHECK9                      1019
#define IDS_STRING1019                  1019
#define IDC_IDC_LOITERS_EDIT            1019
#define IDC_CHECK10                     1020
#define IDS_STRING1020                  1020
#define IDC_LEFTBEHIND_EDIT             1020
#define IDS_STRING1021                  1021
#define IDC_RULENAME                    1021
#define IDS_STRING1022                  1022
#define IDC_VIEW                        1022
#define IDS_STRING1023                  1023
#define IDC_OBJECT                      1023
#define IDS_STRING1024                  1024
#define IDC_CHECK_PERSON                1024
#define IDS_STRING1025                  1025
#define IDC_CHECK_VEHICLE               1025
#define IDC_CHECK_OTHER                 1026
#define IDS_RuleName                    1026
#define IDC_CHECK_ALL                   1027
#define IDS_View                        1027
#define IDC_TIME                        1028
#define IDS_Vertical_View               1028
#define IDC_CHECK_Light_on              1028
#define IDC_LOITERS                     1029
#define IDS_Parallel_View               1029
#define IDC_CHECK_Light_off             1029
#define IDC_LEFTBEHIND                  1030
#define IDS_Object                      1030
#define IDS_Object_Person               1031
#define IDC_Event                       1031
#define IDS_Object_Vehicle              1032
#define IDC_CHECK_Montion               1032
#define IDS_Object_Other                1033
#define IDC_CHECK_Other2                1033
#define IDS_Object_All                  1034
#define IDC_CHECK_Anything              1034
#define IDS_Time_S                      1035
#define IDC_EDIT1                       1035
#define IDS_Loiters_Time                1036
#define IDC_FILTER_ON                   1036
#define IDS_LeftBehind_Time             1037
#define IDC_FILTER_OFF                  1037
#define IDS_RuleName_Alarm              1038
#define IDC_SPIN1                       1038
#define IDS_Object_Alarm                1039
#define IDC_EDIT2                       1039
#define IDS_Event                       1040
#define IDC_Multiplier                  1040
#define IDS_Event_Light_on              1041
#define IDS_Event_Light_off             1042
#define IDS_Event_Montion               1043
#define IDS_Event_Other                 1044
#define IDS_Event_Anything              1045
#define IDS_Filter_MaxObj               1046
#define IDS_Filter_MinObj               1047
#define IDS_Filter_Size_Change          1048
#define IDS_Filter_Shape_Direction      1049
#define IDS_Filter_MaxObj_Info          1050
#define IDS_Filter_MinObj_Info          1051
#define IDS_Filter_Size_Change_Info     1052
#define IDS_Filter_Shape_Direction_Info 1053
#define IDS_Filter_Head_Type            1054
#define IDS_Filter_Head_State           1055
#define IDS_Filter_On                   1056
#define IDS_Filter_Off                  1057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1012
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
